services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.redis.entrypoints=redis"
      - "traefik.tcp.services.redis.loadbalancer.server.port=6379"
      - "homepage.group=Infrastructure"
      - "homepage.name=Redis"
      - "homepage.icon=redis.png"
      - "homepage.description=Key-value store"
    networks:
      - traefik-public
    restart: unless-stopped

networks:
  traefik-public:
    external: true
